receivers:
  otlp:
    protocols:
      grpc: {}
      http: {}

exporters:
  otlp:
    endpoint: "http://tempo:4318"
    insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
