apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: djassa-secrets
  namespace: djassa
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: djassa-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: djassa/database/url
    - secretKey: MOBILE_MONEY_SECRET
      remoteRef:
        key: djassa/mobile_money/secret
    - secretKey: JWT_SECRET
      remoteRef:
        key: djassa/jwt/secret
