apiVersion: v1
kind: ServiceAccount
metadata:
  name: djassa-sa
  namespace: djassa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: djassa
  name: djassa-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: djassa-rolebinding
  namespace: djassa
subjects:
  - kind: ServiceAccount
    name: djassa-sa
    namespace: djassa
roleRef:
  kind: Role
  name: djassa-role
  apiGroup: rbac.authorization.k8s.io
